# Generated by Django 4.2.5 on 2023-09-05 11:38

from django.db import migrations, models
import django.db.models.aggregates
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_title', models.CharField(max_length=255, verbose_name='عنوان فقرة من نحن')),
                ('about_us_content', models.TextField(verbose_name='محتوى فقرة من نحن')),
                ('subscription_title', models.CharField(max_length=255, verbose_name='عنوان نموذج الاشتراك')),
                ('title_products', models.CharField(max_length=255, verbose_name='عنوان المنتجات')),
                ('title_special_products', models.CharField(max_length=255, verbose_name='عنوان المنتجات الاكثر طلبا')),
                ('title_lists', models.CharField(max_length=255, verbose_name='عنوان القوائم الخاصة')),
                ('title_footer', models.CharField(max_length=255, verbose_name='عنوان الفوتر (أسفل الصفحة)')),
                ('contact_title', models.CharField(max_length=255, verbose_name='عنوان صفحة اتصل بنا')),
                ('contact_form_title', models.CharField(max_length=255, verbose_name='عنوان الفورم الخاصة بصفحة اتصل بنا')),
                ('command_title', models.CharField(max_length=255, verbose_name='عنوان صفحة استلام الطلبية ')),
                ('command_details', models.TextField(verbose_name='تفاصيل الطلبية')),
                ('contact_note', models.CharField(max_length=255, verbose_name='ملاحظات الاتصال')),
                ('phone_button', models.CharField(max_length=255, verbose_name='نص زر الاتصال بالهاتف')),
                ('whatsapp_button', models.CharField(max_length=255, verbose_name='نص زر الاتصال بالواتساب')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الاضافة')),
                ('checkout_title', models.CharField(max_length=255, verbose_name='عنوان صفحة تأكيد الطلبية ')),
                ('checkout_button', models.CharField(max_length=255, verbose_name='نص زر التأكيد')),
            ],
            options={
                'verbose_name': 'النصوص و الثوابت',
                'verbose_name_plural': 'النصوص و الثوابت',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255, verbose_name='الايقونة')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الاضافة')),
            ],
            options={
                'verbose_name': 'السمة',
                'verbose_name_plural': 'السمات او الخاصيات',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='الاسم')),
                ('phone', models.EmailField(max_length=30, verbose_name='رقم الهاتف')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الاضافة')),
            ],
            options={
                'verbose_name': 'رسائل المستخدمين',
                'verbose_name_plural': 'رسائل المستخدمين',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الاضافة')),
            ],
            options={
                'verbose_name': 'النوع',
                'verbose_name_plural': 'أنواع المنتجات',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='SettingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=100, verbose_name='عنوان الموقع')),
                ('site_name', models.CharField(max_length=100, verbose_name='اسم الموقع')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية')),
                ('icon', models.ImageField(upload_to='img/', verbose_name='أيقونة الموقع')),
                ('logo', models.ImageField(upload_to='img/', verbose_name='لوجو الموقع')),
                ('main_image', models.ImageField(upload_to='img/', verbose_name='صورةالخلفية الرئيسية')),
                ('about_us_image', models.ImageField(upload_to='img/', verbose_name='صورة فقرة من نحن')),
                ('currency', models.CharField(max_length=30, verbose_name='العملة')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='العنوان')),
                ('phone', models.CharField(max_length=30, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=60, null=True, verbose_name='البريد الإلكتروني')),
                ('whatsapp', models.BooleanField(default=True, verbose_name='خاصية الاتصال بواتساب')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='انستجرام')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='فيسبوك')),
                ('phone_feature', models.BooleanField(default=True, verbose_name='خاصية الاتصال بالهاتف')),
                ('imogie', models.BooleanField(default=True, verbose_name='الايموجي')),
                ('contact_section', models.BooleanField(default=True, verbose_name='قسم التواصل')),
                ('end_order', models.BooleanField(default=False, help_text='هل تريد المستخدم ان يستطيع الولوج الى الصفحة النهائية ( استلام الطلبية ) دائما ؟', verbose_name='الولج الى صفحة استلام الطلبية')),
                ('color', models.CharField(help_text='أدخل اللون (مثل #FF0000 أو red)', max_length=20, verbose_name=' اللون الرئيسي')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الاضافة')),
            ],
            options={
                'verbose_name': 'اعدادات الموقع',
                'verbose_name_plural': 'اعدادات الموقع',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='المدينة')),
                ('price', models.IntegerField(verbose_name='الثمن')),
                ('state', models.BooleanField(default=True, verbose_name='الحالة')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الاضافة')),
            ],
            options={
                'verbose_name': 'المدينة',
                'verbose_name_plural': 'المدن',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=30, verbose_name='رقم الهاتف')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الاضافة')),
            ],
            options={
                'verbose_name': 'المشترك',
                'verbose_name_plural': 'المشتركين',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('max_quantity', models.IntegerField(default=30, verbose_name='أقصى قيمة')),
                ('old_price', models.IntegerField(blank=True, null=True, verbose_name='ثمن المنتوج قبل التخفيض')),
                ('price', models.IntegerField(verbose_name='ثمن المنتوج')),
                ('image', models.ImageField(upload_to='products/', verbose_name='الصورة')),
                ('state', models.BooleanField(default=True, verbose_name='حالة المنتج')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الاضافة')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.producttype', verbose_name='نوع المنتوج')),
            ],
            options={
                'verbose_name': 'المنتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, verbose_name='رقم الطلبية')),
                ('customer', models.CharField(max_length=70, verbose_name='العميل')),
                ('phone_number', models.CharField(max_length=70, verbose_name='رقم الهاتف')),
                ('address', models.CharField(max_length=255, verbose_name='العنوان')),
                ('state', models.BooleanField(default=False, verbose_name='الحالة')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظة')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الاضافة')),
                ('city', models.ForeignKey(on_delete=django.db.models.aggregates.Aggregate, to='main.shipping', verbose_name='المدينة')),
            ],
            options={
                'verbose_name': 'الطلبية',
                'verbose_name_plural': 'الطلبيات',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='ListProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='اسم القائمة')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الاضافة')),
                ('products', models.ManyToManyField(related_name='lists', to='main.product')),
            ],
            options={
                'verbose_name': 'القائمة',
                'verbose_name_plural': 'قوائم المنتجات',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الاضافة')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.order', verbose_name='الطلبية')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'منتج الطلبية',
                'verbose_name_plural': 'منتجات الطلبيات',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='BigProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الاضافة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
            options={
                'verbose_name': 'المنتج',
                'verbose_name_plural': 'المنتجات الأكثر طلبا',
                'ordering': ['-created_on'],
            },
        ),
    ]
