# Generated by Django 4.2.5 on 2023-09-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='رقم الهاتف'),
        ),
    ]
